package com.sidekey.chat.model;

/**
 * MessageType — all structured message types in SideKey.
 *
 * TEXT     → normal chat message from user
 * SYSTEM   → generated by the app (e.g. "User connected", "Session ready")
 * PAIRING  → key exchange control packet (handled by PairingManager, not ChatManager)
 * CONTROL  → future use: typing indicator, read receipt, keepalive
 */
public enum MessageType {
    TEXT,
    SYSTEM,
    PAIRING,
    CONTROL
}